### ISSUE TITLE
System.NotSupportedException immediately after loading on Win 10 Build 16278

### ISSUE THREAD

**Issue by snickler** [neemesis/Slave#1]
The following errors in the Application Log

1) 

> Application: Handyman.Core.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NotSupportedException
> 
> Exception Info: System.IO.FileLoadException
>    at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
>    at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
>    at System.Reflection.Assembly.LoadFrom(System.String)
>    at Handyman.Core.Helpers.PluginManager.LoadPlugins(System.ComponentModel.IContainer ByRef)
>    at Handyman.Core.Context..ctor()
>    at Handyman.Core.Context.get_Current()
>    at Handyman.Core.HandymanContext..ctor()
>    at Handyman.Core.Program.Main()

2) 

> Faulting application name: Handyman.Core.exe, version: 1.2.0.0, time stamp: 0x59a308e7
> Faulting module name: KERNELBASE.dll, version: 10.0.16278.1000, time stamp: 0x1159f547
> Exception code: 0xe0434352
> Fault offset: 0x000000000003c648
> Faulting process id: 0x33d0
> Faulting application start time: 0x01d321ff206ae7b7
> Faulting application path: C:\Users\jerem\Documents\Handyman_Release_Latest\Handyman\Handyman.Core.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: ef7f14d1-11c6-43b2-af26-05ebd6e927c3
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by neemesis** [comment]
@snickler from what I can see, there is problem with loading plugins dll's using **System.Reflection.Assembly**. I see that you are running latest dev version of Windows 10, maybe there are some changes in the library that I'm not aware of, since you are getting **NotSupportedException**.
I searched a little bit and I found this [link](https://stackoverflow.com/a/15238782/8333997), also try to download the latest version to see if the error is fixed :)

**Comment by snickler** [comment]
Latest fixes the issue! :)

**Comment by neemesis** [comment]
@snickler that is great.
ps: email me if you have questions about the application, or an idea for new plugin :)

**Comment by snickler** [comment]
Sweet! Will do. I'll probably have a few ideas once I start using it a lot
